version: "3"
services:
  postgres:
    image: postgres:alpine3.18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
